### ISSUE TITLE
Support for SPM (Structured Programming Macros) in Syntax Highlighting

### ISSUE THREAD

**Issue by cybersorcerer** [eclipse/che-che4z-lsp-for-hlasm#33]
**Is your feature request related to a problem? Please describe.**
First of all, thank you guys for this wonderfull extention to VSCode! I was waiting for something like this since years! I am a z/OS systems programmer in germany and do write IBM assembler code since more than 30 years. One of the biggest problems people without a good understanding about assembler lanuguage are facing is the detection of control flow in assembler programs. IBM has tried to address this problem with SPM (Structured Programming Macros). 

**Describe the solution you'd like**
I would like to see the syntax highlighting feature to automatically detect those macros and highlight them properly.

**Describe alternatives you've considered**
None ;-)

**Additional context**
Here is the link to the relevant IBM manual:
 https://www.ibm.com/support/knowledgecenter/en/SSENW6_1.6.0/com.ibm.zos.v2r3.asmk200/ax3.htm

and a screenshot from VSCode:

![image](https://user-images.githubusercontent.com/33680802/79713384-ea5b9b00-82cd-11ea-9469-cdf714aa79b2.png)

**Comment by michalbali256** [comment]
Hello, thank you for your feedback!

In the current version of the extension, you are expected to provide all definitions of macros you are going to use. You should download them from mainframe, save them to a folder in workspace  and then configure proc_grps.json and pgm_conf.json accordingly.

For the future, the problem is that we are not legally allowed to distribute IBM macros with our extension so I am not sure how to proceed. Or are the macros released under some open source license?

**Comment by cybersorcerer** [comment]
Hi,
thank you for your answer. No everything IBM provides for z/OS Systems programming is proprietary. The macro Expansion feature is not really helpful cause all those macros are provided by IBM and they work, but they should be highlighted properly. As you can see from the Manual (link in original post) SPM's are only for maskeing the Code more readable. All i ask for is to highlight them  correctly. There is no need to store them locally on the machine. Consider SPM's just like any other HLASM Statement. All other macros needed for 98% of all z/OS Systems programming needs in z/OS are stored in the following IBM provided Libraries:

SYS1.MACLIB
SYS1.MODGEN
SYS1.SHASMAC

There are some others for CICS, DB2, IMS and MQ but let us start with the real stuff ;-)
The names and Parameters of the macros in those libraries will not change and there will be not a whole lot of new macros going in there. It does also make not a lot of sense to be able to expand into those macros cause all you need to know to use them is the Parameters, Registers to set etc and this is all in the documentation. If you want to have the names of all the macros in those libraries above let me know and i find a way to give them to you. But again i am a happy camper if only the SPMs where recognized and highlighted correctly, just like any other HLASM Statement.

**Comment by asmelko** [comment]
Hi!
I do not like the idea of ignoring the macro expansion of SPMs as they may have some side effects (e.g., defining global variables) that can alter further code generation.

However, the only option that comes into my mind is that the plugin would generate error on unrecognized operation code (as it does already) _and_ would highlight the operand field.

Not generating the error would create a false sense of code correctness in the user that tries to incorporate their SPMs into the code.

**Comment by michalbali256** [comment]
One workaround I see for you right now is to create an empty macro definition for each macro from the libraries you mentioned:
SYS1.MACLIB
SYS1.MODGEN
SYS1.SHASMAC
This will silence the unavailable macro errors and the operands will be highlighted. If you are able to get the list of all such macros from MF then it should not be too hard to write a bash script or something.
So for starters, it could look like this: [SPMs.zip](https://github.com/eclipse/che-che4z-lsp-for-hlasm/files/4510418/SPMs.zip). It seems to me that would bring the expected behavior.

However, in the standard macros (maybe not SPMs, but in general), there are ordinary symbols definitions and global variable symbols definitions that affect the rest of assembly. There may still be many errors regarding missing ordinary symbols, etc.

Is there any particular reason why you don't want to/cannot get the macro definitions from mainframe and then use it locally? Let us understand your use case of the extension (:

**Comment by cybersorcerer** [comment]
Never mind, copying those libraries to a pc is just completely inconveniant. Often at least two sets are needed (one for a new z/OS release). I found another way to make the macros available without having to undergo the inconveniance of maintaining copies. I mounted the PDSes using the Windows NFS client and this does the job. Thanks again for your patience

**Comment by michalbali256** [comment]
Good to hear you found a solution.

We will definitely look into a way to get the standard macros in a more user-friendly way. Or at least make the extension usable without macros as you suggested.

**Comment by Simnbf** [comment]
Is it possible for zowe to be used to copy macros down from zos to your personal machine? Or maybe zowe could find the macros you need and dynamically cache them? It was a pain for me using an FTP client and like cybersorcerer said maintaining multiple versions gets complicated.

**Comment by cybersorcerer** [comment]
@Simnbf is your z/OS NFS Server configured properly? If yes just use NFS on the PDSes like i did. Saves you a lot of BS ;-). By the way, even if you mount or copy the SPM library 
and define it correctly, Syntax highlighting does flag all of them as in error, cause the macros used are not members of ASM.SASMMAC2 (the SPM macro library). You still need to add files with names like IF, DO, SELECT,ENDIF etc. to the macro folder to make syntaxhighlighting at least a little bit happier! But even if you do, it will flag something like DO WHILE=(CY,R5,GT,ZERO) starting from WHILE= as a syntax error! This is why i said strucured programming macro statements should be treated like normal Assembler instructions and not like macros! It simply does not make any sense at all.

**Comment by zimlu02** [comment]
Hi @Simnbf,

to download all members from a dataset you can use the following Zowe CLI command:

zowe files download all-members <DSN> --extension <extension-name> --directory <target-directory>
or the shorter version (with example values):
zowe files dl am sys1.maclib -e hlasm -d ./maclib

The --extension parameter is optional, leaving it out will download members without extension. To see the help issue: zowe files --help

Would this functionality work for you?
If not, could you help me better understand and define your use case and expected behavior?

Thank you!

**Comment by cybersorcerer** [comment]
Hi,
i need to come back to this issue since it is really annoying. I downloaded the macros from ASM.SASMMAC2. The macro names do NOT correspond to the SPM Statements used in the Assembler Programms  (i.e there are no DO, IF, ELSE, SELECT etc) macros in ASM.SASMMAC2. So i created empty files with those names in my macro directory .... just to make the Plugin happy. But it still is not. Please have a look at the attached screen shots to see what i am Talking about. You Need to come up with a better way to deal with SPM's!

![shot3](https://user-images.githubusercontent.com/33680802/80334131-92cea980-8850-11ea-9577-927b42204acf.png)

![shot4](https://user-images.githubusercontent.com/33680802/80334144-9bbf7b00-8850-11ea-9c50-1f60fde21687.png)

**Comment by asmelko** [comment]
Hello, I finally looked at the ASMA.SASMMAC2 macros and found the bug. The problem is that the SPM's there are all defined with a prefix `ASM_`. Then, somewhere in the file ASMMSP there is a sequence of OPSYN statements that get rid of the prefix. However, our plugin do not implement the OPSYN instruction yet.

On the other hand, the implementation of OPSYN will solve all the problems with syntax highlighting and error messages. The error that happened when you created empty macros was that you did not specified keyword parameters in the macro definition (parameters that have default value like ` &VAL=7`).

I will try to deliver the functionality soon.

**Comment by cybersorcerer** [comment]
Hi,
thank you for your answer! I know how i could have circumvented the problem, but i simply did not want to put anymore efford into this. This clearly does not work as expected but it should ;-) Anyway i am Looking Forward to your solution. If i can help, let me know and i will try my best to help

**Comment by Simnbf** [comment]
@zimlu02 I'll give this a try, however I don't think our SP team have zOSMF fully setup so i've got extremely limited use out of zowe.

**Comment by zimlu02** [comment]
> @zimlu02 I'll give this a try, however I don't think our SP team have zOSMF fully setup so i've got extremely limited use out of zowe.

Please let me know if you succeed! Good luck :)

**Comment by asmelko** [comment]
Hi @cybersorcerer,

I may have solved the problem. Now, when you include ASMA.SASMMAC2, the SPMs should be highlighted correctly.
You can find the new vsix [here](https://github.com/eclipse/che-che4z-lsp-for-hlasm/suites/641631075/artifacts/5372005).

I'd be happy if you confirm that it works for you as well.

Regards,
Adam

**Comment by cybersorcerer** [comment]
Hi asmelko,

looks like you nailed it! I deleted all the fake files i had in the macro folder and it looks good now. Do i still need to keep a local copy of ASMA.SASMMAC2?
As a side node, it looks like the other problem i reported (the one with the EQUATES), is gone as well. Something in the new version must have fixed it .... magic i guess :-)

One more question .... I hate red ;-) is there a way to change the coloring of the intructions?

**Comment by asmelko** [comment]
Happy to hear that! The fix will be delivered with the next release!

Yes, you still need to keep a copy of ASMA.SASMMAC2.

Regarding colors, in your VSCode, go to:
File -> Preferences -> Settings -> search for hlasm -> Semantic Highlighting Colors
